# platform :ios, '9.0'

target 'Reviews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Reviews
	pod 'Alamofire', '~> 5.0.0-beta.5'
end
